APE=/sys/src/ape
<$APE/config

LIB=/$objtype/lib/ape/libmp.a

FILES=\
	mpaux\
	mpfmt\
	strtomp\
	mptobe\
	mptober\
	mptole\
	mptolel\
	betomp\
	letomp\
	mpadd\
	mpsub\
	mpcmp\
	mpsel\
	mpfactorial\
	mpmul\
	mpleft\
	mpright\
	mpvecadd\
	mpvecsub\
	mpvecdigmuladd\
	mpveccmp\
	mpvectscmp\
	mpdigdiv\
	mpdiv\
	mpexp\
	mpmod\
	mpmodop\
	mpextendedgcd\
	mpinvert\
	mprand\
	mpnrand\
	crt\
	mptoi\
	mptoui\
	mptov\
	mptouv\
	mpfield\
	cnfield\
	gmfield\

ALLOFILES=${FILES:%=%.$O}

# cull things in the per-machine directories from this list
OFILES=	`{rc ./reduce $O $objtype $ALLOFILES}

HFILES=\
	/sys/include/ape/mp.h\
	../../../../libmp/port/dat.h\

CFILES=${FILES:%=%.c}

UPDATE=\
	mkfile\
	$HFILES\
	$CFILES\

</sys/src/cmd/mksyslib

CFLAGS=$CFLAGS -c -+ -D_POSIX_SOURCE -D_PLAN9_SOURCE -I. -I../../../libmp/port -I/sys/include/ape -I/sys/include

%.$O:	../../../../libmp/port/%.c
	$CC $CFLAGS ../../../../libmp/port/$stem.c
