APE=/sys/src/ape
<$APE/config
LIB=/$objtype/lib/ape/libap.a
OFILES=\
	basename.$O\
	dirname.$O\
	getgrent.$O\
	getpagesize.$O\
	getpwent.$O\
	locale.$O\
	mkfifo.$O\
	pathconf.$O\
	sigset.$O\
	sysconf.$O\
	tzset.$O\

</sys/src/cmd/mksyslib

CFLAGS=$CFLAGS -c -D_POSIX_SOURCE
