</$objtype/mkfile

LIB=/$objtype/lib/libmp.a
FILES=\
	mpaux\
	mpfmt\
	strtomp\
	mptobe\
	mptober\
	mptole\
	mptolel\
	betomp\
	letomp\
	mpadd\
	mpsub\
	mpcmp\
	mpsel\
	mpfactorial\
	mpmul\
	mpleft\
	mpright\
	mpvecadd\
	mpvecsub\
	mpvecdigmuladd\
	mpveccmp\
	mpvectscmp\
	mpdigdiv\
	mpdiv\
	mpexp\
	mpmod\
	mpmodop\
	mpextendedgcd\
	mpinvert\
	mprand\
	mpnrand\
	crt\
	mptoi\
	mptoui\
	mptov\
	mptouv\

ALLOFILES=${FILES:%=%.$O}
# cull things in the per-machine directories from this list
OFILES=	`{rc ./reduce $O $objtype $ALLOFILES}

HFILES=\
	/$objtype/include/u.h\
	/sys/include/mp.h\
	dat.h\

CFILES=${FILES:%=%.c}


UPDATE=mkfile\
	$HFILES\
	$CFILES\

</sys/src/cmd/mksyslib
