</$objtype/mkfile

TEST=\
	add\
	basic\
	diff\
	export\
	ftype\
	lca\
	merge\
	noam\
	range\
	rebase

</sys/src/cmd/mktest

$cputype.git:
	@{cd .. && objtype=$cputype mk install 'BIN=test/'$target}

test:V:	$cputype.git

clean:V:
	rm -f *.[$OS] *.out *.a[$OS] y.tab.? lex.yy.c y.debug y.output [$OS].??* $TARG
	rm -fr scratch $cputype.git
